Update datasource.go
fiskaly/grafana.surrealdb pull request #19
Opened 2024-09-19 15:59 UTC by josselinchevalay

When we have a request with IF and LET statements get last result elements #18

2024-09-25 07:59 UTC, josselinchevalay commented
hello @ppaulweber are you check my change ? 

Regards

2024-09-25 08:30 UTC, ppaulweber requested changes
@josselinchevalay looks good so far, can you also provide in the provisioned dashboard an example use case of the `let` statement results fetching, see: https://github.com/fiskaly/grafana.surrealdb/blob/master/etc/provisioning/dashboards/Default/default.json

2024-09-25 11:17 UTC, josselinchevalay commented
i add a table elements into default dashboard

2024-10-21 12:51 UTC, josselinchevalay commented
@ppaulweber any news about it ?

2024-11-11 17:38 UTC, ppaulweber commented
I've just re-requested the review ... I'll take care of this ASAP.

2026-05-29 08:58 UTC, ppaulweber approved these changes

2026-05-29 08:58 UTC, merged